### ISSUE TITLE
invalid `ip link` example in README

### ISSUE THREAD

**Issue by phoracek** [kubevirt/bridge-marker#3]
```
[phoracek@t470s ~]$ sudo ip link add test type testBridge
Error: Unknown device type.
```

I believe it should be

```
ip link add test-bridge type bridge
```

**Comment by dankenigsberg** [comment]
OMG, I did not know that I have merge rights!
I never expected https://github.com/kubevirt/bridge-marker/commit/3636f02d285edf8404c69b344cbe0f7a67a4ef96 to be immediately merged. Please revert it if it is horrible.
